// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB540_FrIl86_su13fv4fiYlmCLJhb3mRI',
    appId: '1:819658524875:web:5ecc37eaf30a178a1e334e',
    messagingSenderId: '819658524875',
    projectId: 'takecare-669fe',
    authDomain: 'takecare-669fe.firebaseapp.com',
    storageBucket: 'takecare-669fe.appspot.com',
    measurementId: 'G-X2BN1DVJ71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQU2WgSgIbKm1YU3iKY43eOtRl03kl6qU',
    appId: '1:819658524875:android:804854ea79502b481e334e',
    messagingSenderId: '819658524875',
    projectId: 'takecare-669fe',
    storageBucket: 'takecare-669fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrdMhVBlZNIGDUfCVIE6LJ-6btmYTyVZo',
    appId: '1:819658524875:ios:e28d071f797327e61e334e',
    messagingSenderId: '819658524875',
    projectId: 'takecare-669fe',
    storageBucket: 'takecare-669fe.appspot.com',
    androidClientId: '819658524875-87h3pedrkobcver6aofahdhtrjgm75gm.apps.googleusercontent.com',
    iosClientId: '819658524875-e44c76rel4rp3p131pdqck6vglgd5rlf.apps.googleusercontent.com',
    iosBundleId: 'com.example.takecare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrdMhVBlZNIGDUfCVIE6LJ-6btmYTyVZo',
    appId: '1:819658524875:ios:bb7451385b6369321e334e',
    messagingSenderId: '819658524875',
    projectId: 'takecare-669fe',
    storageBucket: 'takecare-669fe.appspot.com',
    androidClientId: '819658524875-87h3pedrkobcver6aofahdhtrjgm75gm.apps.googleusercontent.com',
    iosClientId: '819658524875-iegml8cm081uac43o0jqi1ebmaid6kdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.takecare.RunnerTests',
  );
}
