// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXpWwIbthPEEXDUKYKtX_qVeZ3RGlAGO0',
    appId: '1:129204740589:web:44fcbf607086274fa9c7e4',
    messagingSenderId: '129204740589',
    projectId: 'takecare-164c6',
    authDomain: 'takecare-164c6.firebaseapp.com',
    storageBucket: 'takecare-164c6.appspot.com',
    measurementId: 'G-DFD3GMYJWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcLSGEZhlXAbiy8XEvsj7jpt-jh8vfllQ',
    appId: '1:129204740589:android:e1002771f467ab57a9c7e4',
    messagingSenderId: '129204740589',
    projectId: 'takecare-164c6',
    storageBucket: 'takecare-164c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-9n9S-YjLkWI5lFoWGQx4bXU4nGLoehU',
    appId: '1:129204740589:ios:75ec7b79d6f0bceca9c7e4',
    messagingSenderId: '129204740589',
    projectId: 'takecare-164c6',
    storageBucket: 'takecare-164c6.appspot.com',
    iosBundleId: 'com.example.takecare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-9n9S-YjLkWI5lFoWGQx4bXU4nGLoehU',
    appId: '1:129204740589:ios:014863566144fcb7a9c7e4',
    messagingSenderId: '129204740589',
    projectId: 'takecare-164c6',
    storageBucket: 'takecare-164c6.appspot.com',
    iosBundleId: 'com.example.takecare.RunnerTests',
  );
}
